[package]
name = "jotting"
authors = ["JacobX <jacobbishopxy@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
lazy_static = "1"
nom = "7"
polars = "0"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1"
thiserror = "1"
